AWSTemplateFormatVersion: 2010-09-09
Description: Plantilla AWS crear un Security Group configurando el grupo para permitir el tráfico SSH de entrada desde cualquier dirección ip

Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow ssh to client host
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0