AWSTemplateFormatVersion: 2010-09-09
Description: Plantilla basica para grupo de seguridad ssh + tomcat

Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: SshAndTomcat
      GroupDescription: Grupo de Seguridad para Tomcat
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0

Outputs:
  SecurityGroupId:
    Description: ID del Grupo de Seguridad para Tomcat
    Value: !Ref SecurityGroup
    Export:
      Name: !Sub "${AWS::StackName}-SecurityGroupId"
