AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Plantilla Backend.

Parameters:
  NombreInstancia:
    Description: Nombre de la instancia
    Type: String

  AMI:
    Description: Imagen SO
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/canonical/ubuntu/server/jammy/stable/current/amd64/hvm/ebs-gp2/ami-id

  VPC:
    Description: VPC
    Type: AWS::EC2::VPC::Id

  KeyName:
    Description: Par de llaves
    Type: AWS::EC2::KeyPair::KeyName
    Default: vockey

  InstanceType:
    Description: Recursos instancia
    Type: String
    Default: t2.large
    AllowedValues:
      - t2.micro
      - t2.large

Resources:
  InstanciaEC2:
    Type: AWS::EC2::Instance
    CreationPolicy:
      ResourceSignal:
        Timeout: PT5M
        Count: 1
    Properties:
      Tags:
        - Key: Name
          Value: !Ref NombreInstancia
      ImageId: !Ref AMI
      InstanceType: !Ref InstanceType      
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - Fn::ImportValue: BackendSecurityGroup
        - Fn::ImportValue: SshSecurityGroup
      UserData:
        Fn::Base64: 
          !Sub |
            #!/bin/bash -xe
            exec > /tmp/userdata.log 2>&1
            #====================================================================#
            # PREPARAR BOOTSTRAP DE CFN HELPER SCRIPTS
            #====================================================================#
            apt update -y
            apt install python3-pip -y
            pip3 install https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-py3-latest.tar.gz
            ln -s /usr/local/init/ubuntu/cfn-hup /etc/init.d/cfn-hup
            #====================================================================#

            sudo sed -i 's/^\$nrconf{restart} = "i";/\$nrconf{restart} = "a";/' /etc/needrestart/needrestart.conf
            sudo sed -i 's/^\$nrconf{kernelhints} = -1;/\$nrconf{kernelhints} = -1;/' /etc/needrestart/needrestart.conf
            sudo sed -i 's/^\$nrconf{checks} = 1;/\$nrconf{checks} = 0;/' /etc/needrestart/needrestart.conf

            apt upgrade -y

            useradd -m -d /opt/tomcat -U -s /bin/false tomcat

            apt install openjdk-21-jdk -y

            cd /tmp

            wget https://dlcdn.apache.org/tomcat/tomcat-11/v11.0.2/bin/apache-tomcat-11.0.2.tar.gz
            tar xzvf apache-tomcat-11*tar.gz -C /opt/tomcat --strip-components=1

            chown -R tomcat:tomcat /opt/tomcat/
            chmod -R u+x /opt/tomcat/bin

            sed -i '/<\/tomcat-users>/i \
            <role rolename="manager-gui" />\n<user username="manager" password="manager_password" roles="manager-gui" />\n<role rolename="admin-gui" />\n<user username="admin" password="admin_password" roles="manager-gui,admin-gui" />' /opt/tomcat/conf/tomcat-users.xml

            sed -i '/<Valve /,/\/>/ s|<Valve|<!--<Valve|; /<Valve /,/\/>/ s|/>|/>-->|' /opt/tomcat/webapps/manager/META-INF/context.xml
            sed -i '/<Valve /,/\/>/ s|<Valve|<!--<Valve|; /<Valve /,/\/>/ s|/>|/>-->|' /opt/tomcat/webapps/host-manager/META-INF/context.xml

            echo '[Unit]
            Description=Tomcat
            After=network.target

            [Service]
            Type=forking

            User=tomcat
            Group=tomcat

            Environment="JAVA_HOME=/usr/lib/jvm/java-1.21.0-openjdk-amd64"
            Environment="JAVA_OPTS=-Djava.security.egd=file:///dev/urandom"
            Environment="CATALINA_BASE=/opt/tomcat"
            Environment="CATALINA_HOME=/opt/tomcat"
            Environment="CATALINA_PID=/opt/tomcat/temp/tomcat.pid"
            Environment="CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC"

            ExecStart=/opt/tomcat/bin/startup.sh
            ExecStop=/opt/tomcat/bin/shutdown.sh

            RestartSec=10
            Restart=always

            [Install]
            WantedBy=multi-user.target' | sudo tee /etc/systemd/system/tomcat.service

            systemctl daemon-reload
            systemctl start tomcat
            systemctl enable tomcat

            cd /tmp

            git clone https://github.com/DavidHormigoRamirez/studentify 
            
            chmod ugo+x studentify/gradlew
            
            cd studentify/

            ./gradlew build

            cp build/libs/studentify-1.0.0.war /opt/tomcat/webapps/studentify.war

            #====================================================================#
            # Este tiene que ser tu ultima instruccion del script
            # Recuerda modificar el valor del --resource al id lógico de la instancia
            /usr/local/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource InstanciaEC2 --region ${AWS::Region}

Outputs:
  IPPrivada:
    Description: IP privada Backend2
    Value: !GetAtt InstanciaEC2.PrivateIp
    Export:
      Name: PrivateIpBack2
  IPublica:
    Description: IP publica Backend2
    Value: !GetAtt InstanciaEC2.PublicIp
    Export:
      Name: PublicIpBack2
