#Elias
AWSTemplateFormatVersion: 2010-09-09
Description: Plantilla AWS Elias Cloudformation

Resources:
  MyFirstBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref AWS::AccountId

