#Elias
AWSTemplateFormatVersion: 2010-09-09
Description: Plantilla AWS crear un Security Group configurando el grupo para permitir el tráfico SSH de entrada desde cualquier dirección ip, con una instancia EC2 t2.small

Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Grupo de Seguridad AWS
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
  
  InstanciaEC2:
    Type: AWS::EC2::Instance
    Properties:
      Tags:
        - Key: Name
          Value: Instancia AWS EC2
      ImageId: ami-04b4f1a9cf54c11d0
      InstanceType: t2.small
      KeyName: vockey
      SecurityGroups:
      - Ref: SecurityGroup